// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "url": "http://www.swagger.io/support",
            "email": "support@swagger.io"
        },
        "license": {
            "name": "MIT",
            "url": "https://opensource.org/licenses/MIT"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/bookings": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "bookings"
                ],
                "summary": "Listar todas las reservas",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/presentation.BookingResponse"
                            }
                        }
                    }
                }
            },
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "bookings"
                ],
                "summary": "Crear una nueva reserva",
                "parameters": [
                    {
                        "description": "Datos de la reserva",
                        "name": "booking",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/presentation.CreateBookingRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/presentation.BookingResponse"
                        }
                    }
                }
            }
        },
        "/api/bookings/pista/{pistaId}/date/{date}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "bookings"
                ],
                "summary": "Obtener reservas por pista y fecha",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID de la pista",
                        "name": "pistaId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Fecha (YYYY-MM-DD)",
                        "name": "date",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/presentation.BookingResponse"
                            }
                        }
                    }
                }
            }
        },
        "/api/bookings/{id}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "bookings"
                ],
                "summary": "Obtener reserva por ID",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID de la reserva",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/presentation.BookingResponse"
                        }
                    }
                }
            },
            "put": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "bookings"
                ],
                "summary": "Actualizar una reserva",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID de la reserva",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Datos a actualizar",
                        "name": "booking",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/presentation.UpdateBookingRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/presentation.BookingResponse"
                        }
                    }
                }
            },
            "delete": {
                "tags": [
                    "bookings"
                ],
                "summary": "Eliminar una reserva",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID de la reserva",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    }
                }
            }
        },
        "/api/bookings/{id}/cancel": {
            "post": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "bookings"
                ],
                "summary": "Cancelar una reserva",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID de la reserva",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/presentation.BookingResponse"
                        }
                    }
                }
            }
        },
        "/api/classes": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "classes"
                ],
                "summary": "Listar todas las clases",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/presentation.ClassResponse"
                            }
                        }
                    }
                }
            },
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "classes"
                ],
                "summary": "Crear una nueva clase",
                "parameters": [
                    {
                        "description": "Datos de la clase",
                        "name": "class",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/presentation.CreateClassRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/presentation.ClassResponse"
                        }
                    }
                }
            }
        },
        "/api/classes/instructor/{instructorId}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "classes"
                ],
                "summary": "Obtener clases por instructor",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID del instructor",
                        "name": "instructorId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/presentation.ClassResponse"
                            }
                        }
                    }
                }
            }
        },
        "/api/classes/{slug}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "classes"
                ],
                "summary": "Obtener clase por slug",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Slug de la clase",
                        "name": "slug",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/presentation.ClassResponse"
                        }
                    }
                }
            },
            "put": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "classes"
                ],
                "summary": "Actualizar una clase",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Slug de la clase",
                        "name": "slug",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Datos a actualizar",
                        "name": "class",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/presentation.UpdateClassRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/presentation.ClassResponse"
                        }
                    }
                }
            },
            "delete": {
                "tags": [
                    "classes"
                ],
                "summary": "Eliminar una clase",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Slug de la clase",
                        "name": "slug",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    }
                }
            }
        },
        "/api/classes/{slug}/cancel": {
            "post": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "classes"
                ],
                "summary": "Cancelar una clase",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Slug de la clase",
                        "name": "slug",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/presentation.ClassResponse"
                        }
                    }
                }
            }
        },
        "/api/classes/{slug}/enroll": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "enrollments"
                ],
                "summary": "Inscribir usuario en una clase",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Slug de la clase",
                        "name": "slug",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Datos de inscripción",
                        "name": "enrollment",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/presentation.EnrollUserRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/classes/{slug}/enrollments": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "enrollments"
                ],
                "summary": "Obtener inscripciones de una clase",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID de la clase",
                        "name": "classID",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/presentation.EnrollmentResponse"
                            }
                        }
                    }
                }
            }
        },
        "/api/enrollments/{id}": {
            "delete": {
                "tags": [
                    "enrollments"
                ],
                "summary": "Cancelar inscripción de un usuario",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID de la inscripción",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    }
                }
            }
        },
        "/api/payments": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "payments"
                ],
                "summary": "Procesar un pago",
                "parameters": [
                    {
                        "description": "Datos del pago",
                        "name": "payment",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/presentation.CreatePaymentRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/presentation.PaymentResponse"
                        }
                    }
                }
            }
        },
        "/api/payments/booking": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "payments"
                ],
                "summary": "Procesar pago de reserva",
                "parameters": [
                    {
                        "description": "Datos del pago de reserva",
                        "name": "payment",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/presentation.CreateBookingPaymentRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/presentation.PaymentResponse"
                        }
                    }
                }
            }
        },
        "/api/payments/class": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "payments"
                ],
                "summary": "Procesar pago de clase",
                "parameters": [
                    {
                        "description": "Datos del pago de clase",
                        "name": "payment",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/presentation.CreateClassPaymentRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/presentation.PaymentResponse"
                        }
                    }
                }
            }
        },
        "/api/payments/club": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "payments"
                ],
                "summary": "Procesar pago de membresía",
                "parameters": [
                    {
                        "description": "Datos del pago de membresía",
                        "name": "payment",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/presentation.CreateClubPaymentRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/presentation.PaymentResponse"
                        }
                    }
                }
            }
        },
        "/api/payments/refund": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "payments"
                ],
                "summary": "Reembolsar un pago",
                "parameters": [
                    {
                        "description": "Datos del reembolso",
                        "name": "refund",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/presentation.RefundPaymentRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/features_payments_presentation.MessageResponse"
                        }
                    }
                }
            }
        },
        "/api/payments/user/{user_id}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "payments"
                ],
                "summary": "Obtener pagos de usuario",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "User ID",
                        "name": "user_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/presentation.PaymentResponse"
                            }
                        }
                    }
                }
            }
        },
        "/api/payments/{id}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "payments"
                ],
                "summary": "Obtener pago por ID",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Payment ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/presentation.PaymentResponse"
                        }
                    }
                }
            }
        },
        "/api/pistas": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "pistas"
                ],
                "summary": "Listar pistas con filtros avanzados",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Búsqueda por nombre o ubicación",
                        "name": "q",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filtro por tipo de deporte (FUTBOL, TENIS, BALONCESTO, PADEL, POLIDEPORTIVA)",
                        "name": "deporte",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Precio mínimo por hora (en euros)",
                        "name": "min_price",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Precio máximo por hora (en euros)",
                        "name": "max_price",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "default": "id_desc",
                        "description": "Ordenación: precio_asc, precio_desc, nombre_asc, nombre_desc",
                        "name": "sort",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 1,
                        "description": "Número de página",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 12,
                        "description": "Items por página",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/presentation.PistaPagedResponse"
                        }
                    }
                }
            },
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "pistas"
                ],
                "summary": "Crear una nueva pista",
                "parameters": [
                    {
                        "description": "Datos de la pista",
                        "name": "pista",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/presentation.CreatePistaRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/presentation.PistaResponse"
                        }
                    }
                }
            }
        },
        "/api/pistas/{id}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "pistas"
                ],
                "summary": "Obtener pista por ID",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID de la pista",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/presentation.PistaResponse"
                        }
                    }
                }
            },
            "put": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "pistas"
                ],
                "summary": "Actualizar una pista",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID de la pista",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Datos a actualizar",
                        "name": "pista",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/presentation.UpdatePistaRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/presentation.PistaResponse"
                        }
                    }
                }
            },
            "delete": {
                "tags": [
                    "pistas"
                ],
                "summary": "Eliminar una pista",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID de la pista",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    }
                }
            }
        },
        "/api/roles": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "roles"
                ],
                "summary": "Listar todos los roles",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/presentation.RoleDTO"
                            }
                        }
                    }
                }
            }
        },
        "/api/users": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Listar todos los usuarios",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Filtrar por rol",
                        "name": "role_id",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/presentation.UserResponse"
                            }
                        }
                    }
                }
            },
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Crear un nuevo usuario",
                "parameters": [
                    {
                        "description": "Datos del usuario",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/presentation.CreateUserRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/presentation.UserResponse"
                        }
                    }
                }
            }
        },
        "/api/users/{slug}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Obtener usuario por slug",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Slug del usuario",
                        "name": "slug",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/presentation.UserResponse"
                        }
                    }
                }
            },
            "put": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Actualizar un usuario",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Slug del usuario",
                        "name": "slug",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Datos a actualizar",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/presentation.UpdateUserRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/presentation.UserResponse"
                        }
                    }
                }
            },
            "delete": {
                "tags": [
                    "users"
                ],
                "summary": "Eliminar un usuario",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Slug del usuario",
                        "name": "slug",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    }
                }
            }
        },
        "/clubs": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Clubs"
                ],
                "summary": "Lista todos los clubs",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/presentation.ClubResponse"
                            }
                        }
                    }
                }
            },
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Clubs"
                ],
                "summary": "Crea un nuevo club",
                "parameters": [
                    {
                        "description": "Datos del club",
                        "name": "club",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/presentation.CreateClubRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/presentation.ClubResponse"
                        }
                    }
                }
            }
        },
        "/clubs/memberships/{id}": {
            "delete": {
                "tags": [
                    "Clubs"
                ],
                "summary": "Elimina un miembro de un club",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Membership ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    }
                }
            }
        },
        "/clubs/memberships/{id}/billing-date": {
            "put": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Clubs"
                ],
                "summary": "Actualiza la fecha de próximo cobro",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Membership ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Nueva fecha",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/presentation.UpdateBillingDateRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/features_clubs_presentation.MessageResponse"
                        }
                    }
                }
            }
        },
        "/clubs/memberships/{id}/cancel": {
            "post": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Clubs"
                ],
                "summary": "Cancela permanentemente una membresía",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Membership ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/features_clubs_presentation.MessageResponse"
                        }
                    }
                }
            }
        },
        "/clubs/memberships/{id}/renew": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Clubs"
                ],
                "summary": "Renueva una membresía procesando el pago",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Membership ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Datos del pago",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/presentation.RenewMembershipRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/features_clubs_presentation.MessageResponse"
                        }
                    }
                }
            }
        },
        "/clubs/memberships/{id}/resume": {
            "post": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Clubs"
                ],
                "summary": "Reanuda una membresía suspendida",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Membership ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/features_clubs_presentation.MessageResponse"
                        }
                    }
                }
            }
        },
        "/clubs/memberships/{id}/suspend": {
            "post": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Clubs"
                ],
                "summary": "Suspende una membresía",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Membership ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/features_clubs_presentation.MessageResponse"
                        }
                    }
                }
            }
        },
        "/clubs/{slug}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Clubs"
                ],
                "summary": "Obtiene un club por slug",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Club slug",
                        "name": "slug",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/presentation.ClubResponse"
                        }
                    }
                }
            },
            "put": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Clubs"
                ],
                "summary": "Actualiza un club existente",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Club slug",
                        "name": "slug",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Datos del club",
                        "name": "club",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/presentation.UpdateClubRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/presentation.ClubResponse"
                        }
                    }
                }
            },
            "delete": {
                "tags": [
                    "Clubs"
                ],
                "summary": "Elimina un club",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Club slug",
                        "name": "slug",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    }
                }
            }
        },
        "/clubs/{slug}/members": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Clubs"
                ],
                "summary": "Obtiene los miembros de un club",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Club slug",
                        "name": "slug",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/presentation.ClubMembershipResponse"
                            }
                        }
                    }
                }
            },
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Clubs"
                ],
                "summary": "Añade un miembro a un club",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Club slug",
                        "name": "slug",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Datos del miembro",
                        "name": "member",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/presentation.AddMemberRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/presentation.ClubMembershipResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "features_clubs_presentation.MessageResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                }
            }
        },
        "features_payments_presentation.MessageResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                }
            }
        },
        "presentation.AddMemberRequest": {
            "type": "object",
            "required": [
                "userSlug"
            ],
            "properties": {
                "userSlug": {
                    "type": "string"
                }
            }
        },
        "presentation.BookingResponse": {
            "type": "object",
            "properties": {
                "createdAt": {
                    "type": "string"
                },
                "endTime": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "notes": {
                    "type": "string"
                },
                "paymentStatus": {
                    "type": "string"
                },
                "pistaId": {
                    "type": "integer"
                },
                "pistaName": {
                    "type": "string"
                },
                "pistaType": {
                    "type": "string"
                },
                "priceSnapshotCents": {
                    "type": "integer"
                },
                "priceSnapshotEuros": {
                    "description": "Convertido a euros para UI",
                    "type": "number"
                },
                "startTime": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                },
                "userId": {
                    "type": "integer"
                },
                "userName": {
                    "type": "string"
                }
            }
        },
        "presentation.ClassResponse": {
            "type": "object",
            "properties": {
                "capacity": {
                    "type": "integer"
                },
                "createdAt": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "endTime": {
                    "type": "string"
                },
                "enrolledCount": {
                    "type": "integer"
                },
                "enrollments": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/presentation.EnrollmentResponse"
                    }
                },
                "id": {
                    "type": "integer"
                },
                "instructorId": {
                    "type": "integer"
                },
                "instructorName": {
                    "type": "string"
                },
                "pistaId": {
                    "type": "integer"
                },
                "pistaName": {
                    "type": "string"
                },
                "priceCents": {
                    "type": "integer"
                },
                "priceEuros": {
                    "type": "number"
                },
                "slug": {
                    "type": "string"
                },
                "startTime": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        },
        "presentation.ClubMembershipResponse": {
            "type": "object",
            "properties": {
                "clubId": {
                    "type": "integer"
                },
                "clubName": {
                    "type": "string"
                },
                "clubSlug": {
                    "type": "string"
                },
                "createdAt": {
                    "type": "string"
                },
                "endDate": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "isActive": {
                    "type": "boolean"
                },
                "nextBillingDate": {
                    "type": "string"
                },
                "paymentStatus": {
                    "type": "string"
                },
                "startDate": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                },
                "userEmail": {
                    "type": "string"
                },
                "userId": {
                    "type": "integer"
                },
                "userName": {
                    "type": "string"
                },
                "userSlug": {
                    "type": "string"
                }
            }
        },
        "presentation.ClubResponse": {
            "type": "object",
            "properties": {
                "createdAt": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "isActive": {
                    "type": "boolean"
                },
                "logoUrl": {
                    "type": "string"
                },
                "maxMembers": {
                    "type": "integer"
                },
                "memberCount": {
                    "type": "integer"
                },
                "monthlyFeeCents": {
                    "type": "integer"
                },
                "monthlyFeeEuros": {
                    "type": "number"
                },
                "name": {
                    "type": "string"
                },
                "ownerId": {
                    "type": "integer"
                },
                "ownerName": {
                    "type": "string"
                },
                "ownerSlug": {
                    "type": "string"
                },
                "slug": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        },
        "presentation.CreateBookingPaymentRequest": {
            "type": "object",
            "required": [
                "amount_cents",
                "booking_id",
                "customer_id",
                "user_id"
            ],
            "properties": {
                "amount_cents": {
                    "type": "integer"
                },
                "booking_id": {
                    "type": "integer"
                },
                "customer_id": {
                    "type": "string"
                },
                "user_id": {
                    "type": "integer"
                }
            }
        },
        "presentation.CreateBookingRequest": {
            "type": "object",
            "required": [
                "endTime",
                "pistaId",
                "startTime"
            ],
            "properties": {
                "endTime": {
                    "type": "string"
                },
                "notes": {
                    "type": "string"
                },
                "pistaId": {
                    "type": "integer",
                    "minimum": 1
                },
                "startTime": {
                    "type": "string"
                },
                "userId": {
                    "type": "integer"
                }
            }
        },
        "presentation.CreateClassPaymentRequest": {
            "type": "object",
            "required": [
                "amount_cents",
                "customer_id",
                "enrollment_id",
                "user_id"
            ],
            "properties": {
                "amount_cents": {
                    "type": "integer"
                },
                "customer_id": {
                    "type": "string"
                },
                "enrollment_id": {
                    "type": "integer"
                },
                "user_id": {
                    "type": "integer"
                }
            }
        },
        "presentation.CreateClassRequest": {
            "type": "object",
            "required": [
                "endTime",
                "instructorId",
                "maxCapacity",
                "pistaId",
                "priceCents",
                "startTime",
                "title"
            ],
            "properties": {
                "description": {
                    "type": "string"
                },
                "endTime": {
                    "type": "string"
                },
                "instructorId": {
                    "type": "integer"
                },
                "maxCapacity": {
                    "type": "integer",
                    "maximum": 20,
                    "minimum": 1
                },
                "pistaId": {
                    "type": "integer"
                },
                "priceCents": {
                    "type": "integer",
                    "minimum": 0
                },
                "startTime": {
                    "type": "string"
                },
                "title": {
                    "type": "string",
                    "minLength": 3
                }
            }
        },
        "presentation.CreateClubPaymentRequest": {
            "type": "object",
            "required": [
                "amount_cents",
                "customer_id",
                "membership_id",
                "user_id"
            ],
            "properties": {
                "amount_cents": {
                    "type": "integer"
                },
                "customer_id": {
                    "type": "string"
                },
                "membership_id": {
                    "type": "integer"
                },
                "user_id": {
                    "type": "integer"
                }
            }
        },
        "presentation.CreateClubRequest": {
            "type": "object",
            "required": [
                "maxMembers",
                "name"
            ],
            "properties": {
                "description": {
                    "type": "string"
                },
                "isActive": {
                    "type": "boolean"
                },
                "logoUrl": {
                    "type": "string"
                },
                "maxMembers": {
                    "type": "integer",
                    "minimum": 1
                },
                "monthlyFeeCents": {
                    "type": "integer",
                    "minimum": 0
                },
                "name": {
                    "type": "string"
                },
                "ownerSlug": {
                    "type": "string"
                }
            }
        },
        "presentation.CreatePaymentRequest": {
            "type": "object",
            "required": [
                "amount_cents",
                "customer_id",
                "description",
                "user_id"
            ],
            "properties": {
                "amount_cents": {
                    "type": "integer"
                },
                "customer_id": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "user_id": {
                    "type": "integer"
                }
            }
        },
        "presentation.CreatePistaRequest": {
            "type": "object",
            "required": [
                "nombre",
                "precio_hora_base",
                "tipo"
            ],
            "properties": {
                "image_url": {
                    "type": "string"
                },
                "nombre": {
                    "type": "string",
                    "maxLength": 100,
                    "minLength": 1
                },
                "precio_hora_base": {
                    "type": "number",
                    "minimum": 0
                },
                "superficie": {
                    "type": "string"
                },
                "tipo": {
                    "type": "string",
                    "enum": [
                        "FUTBOL",
                        "TENIS",
                        "BALONCESTO",
                        "PADEL",
                        "POLIDEPORTIVA"
                    ]
                }
            }
        },
        "presentation.CreateUserRequest": {
            "type": "object",
            "required": [
                "email",
                "fullName",
                "password"
            ],
            "properties": {
                "email": {
                    "type": "string"
                },
                "fullName": {
                    "type": "string"
                },
                "password": {
                    "type": "string",
                    "minLength": 6
                },
                "phone": {
                    "type": "string"
                },
                "roleId": {
                    "type": "integer"
                }
            }
        },
        "presentation.EnrollUserRequest": {
            "type": "object",
            "required": [
                "user_slug"
            ],
            "properties": {
                "user_slug": {
                    "type": "string"
                }
            }
        },
        "presentation.EnrollmentResponse": {
            "type": "object",
            "properties": {
                "classId": {
                    "type": "integer"
                },
                "className": {
                    "type": "string"
                },
                "enrolledAt": {
                    "description": "Alias para compatibilidad",
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "registeredAt": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "userEmail": {
                    "type": "string"
                },
                "userId": {
                    "type": "integer"
                },
                "userName": {
                    "type": "string"
                }
            }
        },
        "presentation.PaymentResponse": {
            "type": "object",
            "properties": {
                "amount_cents": {
                    "type": "integer"
                },
                "amount_euros": {
                    "type": "number"
                },
                "booking_id": {
                    "type": "integer"
                },
                "class_enrollment_id": {
                    "type": "integer"
                },
                "club_membership_id": {
                    "type": "integer"
                },
                "created_at": {
                    "type": "string"
                },
                "currency": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "payment_type": {
                    "type": "string"
                },
                "provider": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "stripe_payment_intent_id": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                },
                "user_id": {
                    "type": "integer"
                }
            }
        },
        "presentation.PistaPagedResponse": {
            "type": "object",
            "properties": {
                "items": {
                    "description": "Tus DTOs de pista normales",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/presentation.PistaResponse"
                    }
                },
                "limit": {
                    "description": "Items por página",
                    "type": "integer"
                },
                "page": {
                    "description": "Página actual",
                    "type": "integer"
                },
                "total": {
                    "description": "Total de resultados en BD",
                    "type": "integer"
                },
                "total_pages": {
                    "description": "Total de páginas",
                    "type": "integer"
                }
            }
        },
        "presentation.PistaResponse": {
            "type": "object",
            "properties": {
                "esActiva": {
                    "type": "boolean"
                },
                "estado": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "imageUrl": {
                    "type": "string"
                },
                "nombre": {
                    "type": "string"
                },
                "precioHoraBase": {
                    "type": "number"
                },
                "superficie": {
                    "type": "string"
                },
                "tipo": {
                    "type": "string"
                }
            }
        },
        "presentation.RefundPaymentRequest": {
            "type": "object",
            "required": [
                "payment_id"
            ],
            "properties": {
                "payment_id": {
                    "type": "integer"
                }
            }
        },
        "presentation.RenewMembershipRequest": {
            "type": "object",
            "required": [
                "customerId"
            ],
            "properties": {
                "customerId": {
                    "type": "string"
                }
            }
        },
        "presentation.RoleDTO": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "presentation.UpdateBillingDateRequest": {
            "type": "object",
            "required": [
                "nextBillingDate"
            ],
            "properties": {
                "nextBillingDate": {
                    "type": "string"
                }
            }
        },
        "presentation.UpdateBookingRequest": {
            "type": "object",
            "required": [
                "endTime",
                "pistaId",
                "startTime"
            ],
            "properties": {
                "endTime": {
                    "type": "string"
                },
                "notes": {
                    "type": "string"
                },
                "paymentStatus": {
                    "type": "string"
                },
                "pistaId": {
                    "type": "integer",
                    "minimum": 1
                },
                "startTime": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "userId": {
                    "type": "integer"
                }
            }
        },
        "presentation.UpdateClassRequest": {
            "type": "object",
            "required": [
                "endTime",
                "instructorId",
                "maxCapacity",
                "pistaId",
                "priceCents",
                "startTime",
                "title"
            ],
            "properties": {
                "description": {
                    "type": "string"
                },
                "endTime": {
                    "type": "string"
                },
                "instructorId": {
                    "type": "integer"
                },
                "maxCapacity": {
                    "type": "integer",
                    "maximum": 20,
                    "minimum": 1
                },
                "pistaId": {
                    "type": "integer"
                },
                "priceCents": {
                    "type": "integer",
                    "minimum": 0
                },
                "startTime": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "title": {
                    "type": "string",
                    "minLength": 3
                }
            }
        },
        "presentation.UpdateClubRequest": {
            "type": "object",
            "required": [
                "maxMembers",
                "name"
            ],
            "properties": {
                "description": {
                    "type": "string"
                },
                "isActive": {
                    "type": "boolean"
                },
                "logoUrl": {
                    "type": "string"
                },
                "maxMembers": {
                    "type": "integer",
                    "minimum": 1
                },
                "monthlyFeeCents": {
                    "type": "integer",
                    "minimum": 0
                },
                "name": {
                    "type": "string"
                },
                "ownerSlug": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "presentation.UpdatePistaRequest": {
            "type": "object",
            "required": [
                "estado",
                "nombre",
                "precio_hora_base",
                "tipo"
            ],
            "properties": {
                "es_activa": {
                    "type": "boolean"
                },
                "estado": {
                    "type": "string",
                    "enum": [
                        "DISPONIBLE",
                        "MANTENIMIENTO",
                        "INACTIVA"
                    ]
                },
                "image_url": {
                    "type": "string"
                },
                "nombre": {
                    "type": "string",
                    "maxLength": 100,
                    "minLength": 1
                },
                "precio_hora_base": {
                    "type": "number",
                    "minimum": 0
                },
                "superficie": {
                    "type": "string"
                },
                "tipo": {
                    "type": "string",
                    "enum": [
                        "FUTBOL",
                        "TENIS",
                        "BALONCESTO",
                        "PADEL",
                        "POLIDEPORTIVA"
                    ]
                }
            }
        },
        "presentation.UpdateUserRequest": {
            "type": "object",
            "properties": {
                "fullName": {
                    "type": "string"
                },
                "isActive": {
                    "type": "boolean"
                },
                "phone": {
                    "type": "string"
                },
                "roleId": {
                    "type": "integer"
                }
            }
        },
        "presentation.UserResponse": {
            "type": "object",
            "properties": {
                "avatarUrl": {
                    "type": "string"
                },
                "createdAt": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "fullName": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "isActive": {
                    "type": "boolean"
                },
                "phone": {
                    "type": "string"
                },
                "roleId": {
                    "type": "integer"
                },
                "roleName": {
                    "type": "string"
                },
                "slug": {
                    "type": "string"
                },
                "stripeCustomerId": {
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/api",
	Schemes:          []string{"http"},
	Title:            "PoliManage API",
	Description:      "API REST para gestión de instalaciones deportivas",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
